/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Onboardings: () => import('#controllers/onboardings_controller'),
  Plans: () => import('#controllers/plans_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  Exercises: () => import('#controllers/exercises_controller'),
  Progresses: () => import('#controllers/progresses_controller'),
  Topics: () => import('#controllers/topics_controller'),
  Claudes: () => import('#controllers/claudes_controller'),
}
