import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Topic from '#models/topic'

export default class TopicsSeeder extends BaseSeeder {
  async run() {
    await Topic.updateOrCreateMany('slug', [

      // ═══════════════════════════════════════════════════════
      // ALGÈBRE
      // ═══════════════════════════════════════════════════════
      {
        slug: 'ensembles-et-logique',
        title: 'Ensembles et Logique',
        description: 'Notions de base : ensembles, sous-ensembles, opérations, quantificateurs.',
        category: 'algebre',
        orderInCategory: 1,
        prerequisites: [],
        difficulty: 1,
        estimatedHours: 2,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques la théorie des ensembles et la logique mathématique de façon intuitive.',
        exercisePrompt: 'Génère un exercice sur les ensembles, les opérations (union, intersection, complémentaire) ou la logique propositionnelle.',
      },
      {
        slug: 'nombres-et-structures',
        title: 'Nombres et Structures Algébriques',
        description: 'Entiers, rationnels, réels, complexes. Groupes, anneaux, corps.',
        category: 'algebre',
        orderInCategory: 2,
        prerequisites: ['ensembles-et-logique'],
        difficulty: 2,
        estimatedHours: 3,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques les structures des nombres et les structures algébriques fondamentales.',
        exercisePrompt: 'Génère un exercice sur les propriétés des nombres ou des structures algébriques.',
      },
      {
        slug: 'polynomes',
        title: 'Polynômes',
        description: 'Opérations, factorisation, racines, théorème de d\'Alembert.',
        category: 'algebre',
        orderInCategory: 3,
        prerequisites: ['nombres-et-structures'],
        difficulty: 2,
        estimatedHours: 3,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques la théorie des polynômes : opérations, factorisation, racines.',
        exercisePrompt: 'Génère un exercice sur la factorisation, les racines ou les opérations sur les polynômes.',
      },
      {
        slug: 'systemes-lineaires',
        title: 'Systèmes Linéaires',
        description: 'Résolution de systèmes d\'équations linéaires, méthode de Gauss.',
        category: 'algebre',
        orderInCategory: 4,
        prerequisites: ['polynomes'],
        difficulty: 2,
        estimatedHours: 3,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques la résolution de systèmes linéaires par substitution, combinaison et méthode de Gauss.',
        exercisePrompt: 'Génère un exercice de résolution d\'un système linéaire (2x2 ou 3x3).',
      },
      {
        slug: 'matrices',
        title: 'Matrices',
        description: 'Opérations matricielles, inverse, déterminant, rang.',
        category: 'algebre',
        orderInCategory: 5,
        prerequisites: ['systemes-lineaires'],
        difficulty: 3,
        estimatedHours: 4,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques les matrices : addition, multiplication, transposée, inverse, déterminant.',
        exercisePrompt: 'Génère un exercice sur les opérations matricielles, le calcul de déterminant ou d\'inverse.',
      },
      {
        slug: 'valeurs-propres',
        title: 'Valeurs Propres et Vecteurs Propres',
        description: 'Diagonalisation, spectre d\'une matrice, applications.',
        category: 'algebre',
        orderInCategory: 6,
        prerequisites: ['matrices'],
        difficulty: 4,
        estimatedHours: 5,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques les valeurs propres, vecteurs propres et la diagonalisation. Relie au monde quantique (observables, états propres).',
        exercisePrompt: 'Génère un exercice sur le calcul de valeurs propres, vecteurs propres ou la diagonalisation d\'une matrice.',
      },
      {
        slug: 'espaces-vectoriels',
        title: 'Espaces Vectoriels',
        description: 'Vecteurs, base, dimension, applications linéaires.',
        category: 'algebre',
        orderInCategory: 7,
        prerequisites: ['matrices'],
        difficulty: 3,
        estimatedHours: 4,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques les espaces vectoriels, les sous-espaces, les bases et la dimension. Prépare le terrain pour l\'espace de Hilbert.',
        exercisePrompt: 'Génère un exercice sur les espaces vectoriels : base, dimension, application linéaire.',
      },

      // ═══════════════════════════════════════════════════════
      // ANALYSE
      // ═══════════════════════════════════════════════════════
      {
        slug: 'fonctions',
        title: 'Fonctions',
        description: 'Définition, domaine, image, parité, composition, bijection.',
        category: 'analyse',
        orderInCategory: 1,
        prerequisites: ['ensembles-et-logique'],
        difficulty: 1,
        estimatedHours: 3,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques les fonctions mathématiques : définition, propriétés, représentation graphique.',
        exercisePrompt: 'Génère un exercice sur les propriétés des fonctions (domaine, parité, bijection, composition).',
      },
      {
        slug: 'limites',
        title: 'Limites',
        description: 'Définition, calcul de limites, formes indéterminées, continuité.',
        category: 'analyse',
        orderInCategory: 2,
        prerequisites: ['fonctions'],
        difficulty: 2,
        estimatedHours: 4,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques les limites de fonctions : définition intuitive et formelle, techniques de calcul, continuité.',
        exercisePrompt: 'Génère un exercice de calcul de limite (formes indéterminées, limites en l\'infini, continuité).',
      },
      {
        slug: 'derivees',
        title: 'Dérivées',
        description: 'Définition, règles de dérivation, interprétation géométrique.',
        category: 'analyse',
        orderInCategory: 3,
        prerequisites: ['limites'],
        difficulty: 2,
        estimatedHours: 4,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques la dérivée : définition comme limite, règles de calcul, interprétation géométrique et physique.',
        exercisePrompt: 'Génère un exercice de calcul de dérivée (règles, dérivées composées, dérivées successives).',
      },
      {
        slug: 'etude-de-fonctions',
        title: 'Étude de Fonctions',
        description: 'Variations, extremums, concavité, asymptotes, tracé.',
        category: 'analyse',
        orderInCategory: 4,
        prerequisites: ['derivees'],
        difficulty: 3,
        estimatedHours: 4,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques comment faire une étude complète de fonction : tableau de variations, extremums, concavité, asymptotes.',
        exercisePrompt: 'Génère un exercice d\'étude complète de fonction ou d\'analyse locale (extremum, concavité).',
      },
      {
        slug: 'integrales',
        title: 'Intégrales',
        description: 'Primitives, intégrale de Riemann, techniques d\'intégration.',
        category: 'analyse',
        orderInCategory: 5,
        prerequisites: ['derivees'],
        difficulty: 3,
        estimatedHours: 5,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques l\'intégrale : définition comme aire, primitives, techniques (substitution, parties, fractions partielles).',
        exercisePrompt: 'Génère un exercice de calcul d\'intégrale (primitive, intégrale définie, technique d\'intégration).',
      },
      {
        slug: 'suites',
        title: 'Suites',
        description: 'Suites arithmétiques, géométriques, convergence, récurrence.',
        category: 'analyse',
        orderInCategory: 6,
        prerequisites: ['limites'],
        difficulty: 2,
        estimatedHours: 3,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques les suites numériques : définitions, convergence, suites classiques.',
        exercisePrompt: 'Génère un exercice sur les suites (terme général, convergence, raisonnement par récurrence).',
      },
      {
        slug: 'series',
        title: 'Séries',
        description: 'Séries numériques, critères de convergence, séries entières.',
        category: 'analyse',
        orderInCategory: 7,
        prerequisites: ['suites', 'integrales'],
        difficulty: 4,
        estimatedHours: 5,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques les séries : convergence, critères (ratio, comparaison), séries de Taylor et de Fourier.',
        exercisePrompt: 'Génère un exercice sur la convergence d\'une série ou le développement en série entière.',
      },
      {
        slug: 'equations-differentielles',
        title: 'Équations Différentielles',
        description: 'EDO du 1er et 2ème ordre, solutions, conditions initiales.',
        category: 'analyse',
        orderInCategory: 8,
        prerequisites: ['integrales'],
        difficulty: 4,
        estimatedHours: 6,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques les équations différentielles ordinaires. Fais le lien avec l\'équation de Schrödinger en physique quantique.',
        exercisePrompt: 'Génère un exercice de résolution d\'équation différentielle (variables séparables, linéaire d\'ordre 1 ou 2).',
      },
      {
        slug: 'transformee-de-fourier',
        title: 'Transformée de Fourier',
        description: 'Analyse fréquentielle, convolution, applications.',
        category: 'analyse',
        orderInCategory: 9,
        prerequisites: ['series', 'integrales'],
        difficulty: 4,
        estimatedHours: 5,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques la transformée de Fourier et son interprétation physique. Relie à la dualité position-impulsion en quantique.',
        exercisePrompt: 'Génère un exercice sur la transformée de Fourier ou l\'analyse de signaux.',
      },

      // ═══════════════════════════════════════════════════════
      // PROBABILITÉS
      // ═══════════════════════════════════════════════════════
      {
        slug: 'probabilites-de-base',
        title: 'Probabilités de Base',
        description: 'Événements, probabilité, conditionnelle, indépendance.',
        category: 'probabilites',
        orderInCategory: 1,
        prerequisites: ['ensembles-et-logique'],
        difficulty: 1,
        estimatedHours: 3,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques les probabilités classiques : axiomes, probabilité conditionnelle, théorème de Bayes.',
        exercisePrompt: 'Génère un exercice de probabilités (calcul de probabilité, probabilité conditionnelle, Bayes).',
      },
      {
        slug: 'variables-aleatoires',
        title: 'Variables Aléatoires',
        description: 'Lois discrètes et continues, espérance, variance.',
        category: 'probabilites',
        orderInCategory: 2,
        prerequisites: ['probabilites-de-base', 'integrales'],
        difficulty: 3,
        estimatedHours: 4,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques les variables aléatoires, les lois de distribution et les moments. Relie à la notion de valeur moyenne en quantique.',
        exercisePrompt: 'Génère un exercice sur les variables aléatoires (loi, espérance, variance, distribution).',
      },

      // ═══════════════════════════════════════════════════════
      // PHYSIQUE CLASSIQUE
      // ═══════════════════════════════════════════════════════
      {
        slug: 'mecanique-newtonienne',
        title: 'Mécanique Newtonienne',
        description: 'Lois de Newton, forces, énergie, quantité de mouvement.',
        category: 'physique_classique',
        orderInCategory: 1,
        prerequisites: ['derivees'],
        difficulty: 2,
        estimatedHours: 4,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques la mécanique classique : lois de Newton, travail, énergie cinétique et potentielle, conservation.',
        exercisePrompt: 'Génère un exercice de mécanique classique (bilan des forces, énergie, mouvement).',
      },
      {
        slug: 'oscillateurs',
        title: 'Oscillateurs',
        description: 'Oscillateur harmonique, amorti, forcé. Résonance.',
        category: 'physique_classique',
        orderInCategory: 2,
        prerequisites: ['mecanique-newtonienne', 'equations-differentielles'],
        difficulty: 3,
        estimatedHours: 4,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques l\'oscillateur harmonique classique et fais le pont vers l\'oscillateur harmonique quantique.',
        exercisePrompt: 'Génère un exercice sur l\'oscillateur harmonique (équation du mouvement, énergie, résonance).',
      },
      {
        slug: 'ondes-classiques',
        title: 'Ondes Classiques',
        description: 'Propagation, interférences, diffraction, équation d\'onde.',
        category: 'physique_classique',
        orderInCategory: 3,
        prerequisites: ['oscillateurs'],
        difficulty: 3,
        estimatedHours: 4,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques les ondes classiques : propagation, superposition, interférences. Prépare à la dualité onde-corpuscule.',
        exercisePrompt: 'Génère un exercice sur les ondes (équation de propagation, interférences, diffraction).',
      },
      {
        slug: 'electromagnetisme',
        title: 'Électromagnétisme',
        description: 'Champs E et B, équations de Maxwell, ondes EM.',
        category: 'physique_classique',
        orderInCategory: 4,
        prerequisites: ['derivees', 'integrales'],
        difficulty: 4,
        estimatedHours: 6,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques l\'électromagnétisme classique et fais le lien avec la quantification du champ électromagnétique (photons).',
        exercisePrompt: 'Génère un exercice d\'électromagnétisme (champ électrique, magnétique, force de Lorentz, induction).',
      },

      // ═══════════════════════════════════════════════════════
      // PHYSIQUE QUANTIQUE
      // ═══════════════════════════════════════════════════════
      {
        slug: 'origines-quantique',
        title: 'Origines de la Physique Quantique',
        description: 'Corps noir, effet photoélectrique, modèle de Bohr, dualité onde-corpuscule.',
        category: 'physique_quantique',
        orderInCategory: 1,
        prerequisites: ['ondes-classiques', 'electromagnetisme'],
        difficulty: 2,
        estimatedHours: 3,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques la naissance de la physique quantique : les expériences historiques qui ont remis en cause la physique classique.',
        exercisePrompt: 'Génère un exercice sur les origines du quantique (énergie des photons, effet photoélectrique, modèle de Bohr).',
      },
      {
        slug: 'postulats-mecanique-quantique',
        title: 'Postulats de la Mécanique Quantique',
        description: 'État quantique, espace de Hilbert, observables, mesure, évolution.',
        category: 'physique_quantique',
        orderInCategory: 2,
        prerequisites: ['origines-quantique', 'espaces-vectoriels', 'valeurs-propres'],
        difficulty: 4,
        estimatedHours: 6,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques les postulats fondamentaux de la mécanique quantique avec rigueur et intuition. C\'est le cœur de la théorie.',
        exercisePrompt: 'Génère un exercice sur les postulats (représentation d\'un état, valeur moyenne d\'une observable, probabilité de mesure).',
      },
      {
        slug: 'fonction-donde',
        title: 'Fonction d\'Onde',
        description: 'ψ(x,t), interprétation probabiliste, normalisation, paquet d\'onde.',
        category: 'physique_quantique',
        orderInCategory: 3,
        prerequisites: ['postulats-mecanique-quantique'],
        difficulty: 4,
        estimatedHours: 5,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques la fonction d\'onde : définition, interprétation de Born, normalisation, paquet d\'ondes gaussien.',
        exercisePrompt: 'Génère un exercice sur la fonction d\'onde (normalisation, densité de probabilité, valeur moyenne de position).',
      },
      {
        slug: 'equation-de-schrodinger',
        title: 'Équation de Schrödinger',
        description: 'Équation dépendante et indépendante du temps, états stationnaires.',
        category: 'physique_quantique',
        orderInCategory: 4,
        prerequisites: ['fonction-donde', 'equations-differentielles'],
        difficulty: 5,
        estimatedHours: 6,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques l\'équation de Schrödinger : dérivation heuristique, équation indépendante du temps, états stationnaires.',
        exercisePrompt: 'Génère un exercice sur l\'équation de Schrödinger (puits infini, barrière de potentiel, états stationnaires).',
      },
      {
        slug: 'principe-incertitude',
        title: 'Principe d\'Incertitude de Heisenberg',
        description: 'Δx·Δp ≥ ℏ/2, interprétation, conséquences physiques.',
        category: 'physique_quantique',
        orderInCategory: 5,
        prerequisites: ['fonction-donde'],
        difficulty: 3,
        estimatedHours: 3,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques le principe d\'incertitude : origine mathématique, interprétation physique, conséquences sur la mesure.',
        exercisePrompt: 'Génère un exercice sur le principe d\'incertitude (calcul d\'incertitude, applications, estimation d\'énergie).',
      },
      {
        slug: 'spin',
        title: 'Spin',
        description: 'Moment angulaire intrinsèque, qubit, sphère de Bloch, matrices de Pauli.',
        category: 'physique_quantique',
        orderInCategory: 6,
        prerequisites: ['postulats-mecanique-quantique', 'matrices'],
        difficulty: 4,
        estimatedHours: 5,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques le spin 1/2 : états |↑⟩ et |↓⟩, matrices de Pauli, représentation sur la sphère de Bloch, mesure.',
        exercisePrompt: 'Génère un exercice sur le spin (états, matrices de Pauli, probabilités de mesure, sphère de Bloch).',
      },
      {
        slug: 'double-fente',
        title: 'Expérience de la Double Fente',
        description: 'Interférences quantiques, effacement de marqueur, paradoxe mesure.',
        category: 'physique_quantique',
        orderInCategory: 7,
        prerequisites: ['fonction-donde', 'principe-incertitude'],
        difficulty: 3,
        estimatedHours: 3,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques l\'expérience de la double fente d\'Young : interférences quantiques, rôle de la mesure, complémentarité.',
        exercisePrompt: 'Génère un exercice sur la double fente (figures d\'interférence, longueur d\'onde de de Broglie, effacement quantique).',
      },
      {
        slug: 'oscillateur-harmonique-quantique',
        title: 'Oscillateur Harmonique Quantique',
        description: 'Niveaux d\'énergie quantifiés, opérateurs création/annihilation, états cohérents.',
        category: 'physique_quantique',
        orderInCategory: 8,
        prerequisites: ['equation-de-schrodinger', 'oscillateurs'],
        difficulty: 5,
        estimatedHours: 6,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques l\'oscillateur harmonique quantique : niveaux d\'énergie E_n = (n+1/2)ℏω, opérateurs échelle, fonctions d\'onde.',
        exercisePrompt: 'Génère un exercice sur l\'oscillateur harmonique quantique (énergies, opérateurs a et a†, états de Fock).',
      },
      {
        slug: 'intrication-quantique',
        title: 'Intrication Quantique',
        description: 'États EPR, non-localité, inégalités de Bell, applications (cryptographie, téléportation).',
        category: 'physique_quantique',
        orderInCategory: 9,
        prerequisites: ['spin', 'postulats-mecanique-quantique'],
        difficulty: 5,
        estimatedHours: 5,
        isQuantum: true,
        isActive: true,
        theoryPrompt: 'Tu expliques l\'intrication quantique : états de Bell, paradoxe EPR, inégalités de Bell, téléportation quantique.',
        exercisePrompt: 'Génère un exercice sur l\'intrication (états de Bell, calcul de corrélations, inégalités de Bell).',
      },

      // ═══════════════════════════════════════════════════════
      // RELATIVITÉ
      // ═══════════════════════════════════════════════════════
      {
        slug: 'relativite-restreinte',
        title: 'Relativité Restreinte',
        description: 'Postulats d\'Einstein, dilatation du temps, contraction des longueurs, E=mc².',
        category: 'relativite',
        orderInCategory: 1,
        prerequisites: ['mecanique-newtonienne', 'electromagnetisme'],
        difficulty: 3,
        estimatedHours: 5,
        isQuantum: false,
        isActive: true,
        theoryPrompt: 'Tu expliques la relativité restreinte : postulats, transformations de Lorentz, conséquences (dilatation du temps, E=mc²).',
        exercisePrompt: 'Génère un exercice de relativité restreinte (dilatation du temps, contraction, énergie relativiste).',
      },
    ])

    console.log('✅ Topics seeder terminé — notions insérées en base.')
  }
}
