/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExerciseSchema extends BaseModel {
  static $columns = ['attempts', 'claudeFeedback', 'correctAnswer', 'createdAt', 'difficulty', 'id', 'isCorrect', 'question', 'questionData', 'sessionId', 'solutionSteps', 'timeSpentSeconds', 'topicId', 'type', 'updatedAt', 'userAnswer'] as const
  $columns = ExerciseSchema.$columns
  @column()
  declare attempts: number | null
  @column()
  declare claudeFeedback: string | null
  @column()
  declare correctAnswer: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare difficulty: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorrect: boolean | null
  @column()
  declare question: string
  @column()
  declare questionData: any | null
  @column()
  declare sessionId: number
  @column()
  declare solutionSteps: any | null
  @column()
  declare timeSpentSeconds: number | null
  @column()
  declare topicId: number
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAnswer: string | null
}

export class LearningPlanSchema extends BaseModel {
  static $columns = ['claudeSummary', 'createdAt', 'endDate', 'id', 'lastAdjustedAt', 'lastAdjustmentReason', 'startDate', 'status', 'updatedAt', 'userId'] as const
  $columns = LearningPlanSchema.$columns
  @column()
  declare claudeSummary: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastAdjustedAt: DateTime | null
  @column()
  declare lastAdjustmentReason: string | null
  @column.date()
  declare startDate: DateTime
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MessageSchema extends BaseModel {
  static $columns = ['claudeMeta', 'content', 'context', 'createdAt', 'feedback', 'hasCode', 'hasLatex', 'id', 'role', 'sessionId', 'userId'] as const
  $columns = MessageSchema.$columns
  @column()
  declare claudeMeta: any | null
  @column()
  declare content: string
  @column()
  declare context: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feedback: string | null
  @column()
  declare hasCode: boolean | null
  @column()
  declare hasLatex: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare sessionId: number | null
  @column()
  declare userId: number
}

export class PlanWeekSchema extends BaseModel {
  static $columns = ['claudeIntro', 'createdAt', 'id', 'learningPlanId', 'objective', 'progressPercent', 'status', 'theme', 'topicIds', 'updatedAt', 'weekNumber'] as const
  $columns = PlanWeekSchema.$columns
  @column()
  declare claudeIntro: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare learningPlanId: number
  @column()
  declare objective: string | null
  @column()
  declare progressPercent: number | null
  @column()
  declare status: string | null
  @column()
  declare theme: string | null
  @column()
  declare topicIds: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weekNumber: number
}

export class ProgressSchema extends BaseModel {
  static $columns = ['correctExercises', 'createdAt', 'currentLevel', 'id', 'lastStudiedAt', 'masteryScore', 'nextReviewAt', 'reviewIntervalDays', 'sessionsCount', 'status', 'topicId', 'totalExercises', 'totalTimeMinutes', 'updatedAt', 'userId'] as const
  $columns = ProgressSchema.$columns
  @column()
  declare correctExercises: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentLevel: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastStudiedAt: DateTime | null
  @column()
  declare masteryScore: number | null
  @column.dateTime()
  declare nextReviewAt: DateTime | null
  @column()
  declare reviewIntervalDays: number | null
  @column()
  declare sessionsCount: number | null
  @column()
  declare status: string | null
  @column()
  declare topicId: number
  @column()
  declare totalExercises: number | null
  @column()
  declare totalTimeMinutes: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SessionSchema extends BaseModel {
  static $columns = ['claudeSessionNotes', 'completedAt', 'createdAt', 'detectedLevel', 'durationMinutes', 'exercisesAttempted', 'exercisesCorrect', 'hintsUsed', 'id', 'learningPlanId', 'performanceScore', 'phase', 'startedAt', 'status', 'topicId', 'updatedAt', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare claudeSessionNotes: string | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detectedLevel: string | null
  @column()
  declare durationMinutes: number | null
  @column()
  declare exercisesAttempted: number | null
  @column()
  declare exercisesCorrect: number | null
  @column()
  declare hintsUsed: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare learningPlanId: number | null
  @column()
  declare performanceScore: number | null
  @column()
  declare phase: string | null
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string | null
  @column()
  declare topicId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TopicSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'difficulty', 'estimatedHours', 'exercisePrompt', 'id', 'isActive', 'isQuantum', 'orderInCategory', 'prerequisites', 'slug', 'theoryPrompt', 'title', 'updatedAt'] as const
  $columns = TopicSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare difficulty: number
  @column()
  declare estimatedHours: number
  @column()
  declare exercisePrompt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isQuantum: boolean
  @column()
  declare orderInCategory: number
  @column()
  declare prerequisites: any | null
  @column()
  declare slug: string
  @column()
  declare theoryPrompt: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'lastActiveAt', 'level', 'minutesPerDay', 'objective', 'onboardingCompleted', 'password', 'preferredTopics', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastActiveAt: DateTime | null
  @column()
  declare level: string | null
  @column()
  declare minutesPerDay: number | null
  @column()
  declare objective: string | null
  @column()
  declare onboardingCompleted: boolean | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare preferredTopics: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
